### ISSUE TITLE
feat: implement responsive UI

### ISSUE THREAD

**Issue by samuray90** [samuray90/30-min#3]
* [x] feat: implement the header image #4
* [x] feat: implement latest news #5
* [x] feat: implement article panel #6
* [x] feat: implement footer #7
* [x] feat: implement custom font icon #12
